export enum AppActionTypes {
    SET_YOUTUBE_VIDEOS = '[APP] SET_YOUTUBE_VIDEOS',
    SET_SELECTED_YOUTUBE_VIDEO = '[APP] SET_SELECTED_YOUTUBE_VIDEO',
    SET_SELECTED_YOUTUBE_VIDEO_COMMENTS = '[APP] SET_SELECTED_YOUTUBE_VIDEO_COMMENTS',
}
